public class SetDemo {
    public void setMethod() {
        //Set<String> strSet = new Set<String>();
        //Set<String> strSet2 = new Set<String>();
        //List<String> strList = new List<String>();
        
        //strSet.add('India');
        //strSet.add('USA');
        //strSet.add('China');
        //strSet.add('UK');
        //strSet.add('India');
        //strSet.add('UK');
		
        //System.debug('strSet =>' + strSet.containsAll(strSet2));
		//strSet2 = strSet.clone();
        
        //boolean ContainsValue = strSet.equals(strSet2);
        //System.debug('strSet2 =>' + ContainsValue);
        
        Set<Id> idSet = new Set<Id>();
    }
}